export const tags =`Wordle,
Wordles,
Wordle creator,
Wordless Spanish,
Slope unblocked ,
Worldscapes online, 
7 letter word,
Wordle maker ,
Word search,
Squabble,
Wordlie,
Free Wordle generator,
Free Wordle,
unilim,
Words game lol,
Wordplay,
Word play,
Wordplays,
Wordables,
Word solver,
Nytmini,
Nytmini crossword,
Wnyt,
World,
Play just words,
Scramble words cheats`